### ISSUE TITLE
Error to projects

### ISSUE THREAD

**Issue by sanzharsp** [livealvi/PointOfSaleProject#2]
Your project does not start, it gives an error
![Снимок экрана 2023-11-09 173231](https://github.com/livealvi/.NET-Point-of-Sale-POS--Csharp/assets/99716421/d56a3eb0-e3d1-437a-89b0-c7c9f3d5dbf7)

**Comment by livealvi** [comment]
@sanzharsp, please read the Readme carefully. This repository doesn't have a database and doesn't have the third-party UI libraries.
